package network

import (
	"errors"
	"os"
	"path/filepath"
	"runtime"
	"testing"
)

func TestListInterfaces(t *testing.T) {
	svc := NewService()
	ifaces, err := svc.ListInterfaces()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if ifaces == nil {
		t.Fatal("expected non-nil slice")
	}
	// Every system should have at least one non-loopback interface
	// (may be zero in some CI containers, so don't assert count)
	for _, iface := range ifaces {
		if iface.Name == "" {
			t.Error("interface with empty name")
		}
		if iface.State != "up" && iface.State != "down" {
			t.Errorf("interface %s: unexpected state %q", iface.Name, iface.State)
		}
	}
}

func TestGetInterface_NotFound(t *testing.T) {
	svc := NewService()
	_, err := svc.GetInterface("nonexistent_iface_99")
	if err == nil {
		t.Fatal("expected error for nonexistent interface")
	}
	if err != errIfaceNotFound {
		t.Errorf("got %v, want errIfaceNotFound", err)
	}
}

func TestValidateStaticIPRequest(t *testing.T) {
	cases := []struct {
		name    string
		req     StaticIPRequest
		wantErr error
	}{
		{"valid", StaticIPRequest{IP: "192.168.1.10/24", Gateway: "192.168.1.1"}, nil},
		{"empty_ip", StaticIPRequest{IP: "", Gateway: "192.168.1.1"}, errEmptyIP},
		{"empty_gw", StaticIPRequest{IP: "192.168.1.10/24", Gateway: ""}, errEmptyGateway},
		{"bad_cidr", StaticIPRequest{IP: "192.168.1.10", Gateway: "192.168.1.1"}, errInvalidCIDR},
		{"bad_gw", StaticIPRequest{IP: "192.168.1.10/24", Gateway: "not-an-ip"}, errInvalidGW},
		{"ipv6_gw", StaticIPRequest{IP: "192.168.1.10/24", Gateway: "::1"}, errIPv6NotSupported},
		{"cidr_v6", StaticIPRequest{IP: "::1/128", Gateway: "192.168.1.1"}, errIPv6NotSupported},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			err := validateStaticIPRequest(tc.req)
			if err != tc.wantErr {
				t.Errorf("got %v, want %v", err, tc.wantErr)
			}
		})
	}
}

func TestSetStaticIP_NonLinux(t *testing.T) {
	if runtime.GOOS == "linux" {
		t.Skip("skipping non-Linux test on Linux")
	}
	svc := NewService()
	_, err := svc.SetStaticIP("eth0", StaticIPRequest{IP: "10.0.0.1/24", Gateway: "10.0.0.254"})
	if err != errNotLinux {
		t.Fatalf("got %v, want errNotLinux", err)
	}
}

func TestSetDNS_NonLinux(t *testing.T) {
	if runtime.GOOS == "linux" {
		t.Skip("skipping non-Linux test on Linux")
	}
	svc := NewService()
	_, err := svc.SetDNS(DNSConfig{Nameservers: []string{"8.8.8.8"}})
	if err != errNotLinux {
		t.Fatalf("got %v, want errNotLinux", err)
	}
}

func TestParseResolvConf(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "resolv.conf")

	content := `# Generated by NetworkManager
nameserver 8.8.8.8
nameserver 1.1.1.1
search local home.lan
`
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("failed to write test file: %v", err)
	}

	cfg, err := parseResolvConf(path)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(cfg.Nameservers) != 2 {
		t.Fatalf("nameservers: got %d, want 2", len(cfg.Nameservers))
	}
	if cfg.Nameservers[0] != "8.8.8.8" || cfg.Nameservers[1] != "1.1.1.1" {
		t.Errorf("nameservers: got %v", cfg.Nameservers)
	}
	if len(cfg.Search) != 2 {
		t.Fatalf("search: got %d, want 2", len(cfg.Search))
	}
	if cfg.Search[0] != "local" || cfg.Search[1] != "home.lan" {
		t.Errorf("search: got %v", cfg.Search)
	}
}

func TestParseResolvConf_MissingFile(t *testing.T) {
	cfg, err := parseResolvConf("/nonexistent/resolv.conf")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cfg.Nameservers == nil || len(cfg.Nameservers) != 0 {
		t.Errorf("expected empty nameservers, got %v", cfg.Nameservers)
	}
}

func TestParseResolvConf_EmptyFile(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "resolv.conf")
	if err := os.WriteFile(path, []byte(""), 0o644); err != nil {
		t.Fatalf("failed to write: %v", err)
	}
	cfg, err := parseResolvConf(path)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(cfg.Nameservers) != 0 {
		t.Errorf("expected empty nameservers, got %v", cfg.Nameservers)
	}
}

func TestParseResolvConf_CommentsOnly(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "resolv.conf")
	content := "# comment\n# another\n"
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("failed to write: %v", err)
	}
	cfg, err := parseResolvConf(path)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(cfg.Nameservers) != 0 {
		t.Errorf("expected empty nameservers, got %v", cfg.Nameservers)
	}
}

func TestGetDNS_WithMockPath(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "resolv.conf")
	content := "nameserver 9.9.9.9\n"
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("failed to write: %v", err)
	}

	svc := &Service{resolvPath: path}
	dns, err := svc.GetDNS()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(dns.Nameservers) != 1 || dns.Nameservers[0] != "9.9.9.9" {
		t.Errorf("nameservers: got %v, want [9.9.9.9]", dns.Nameservers)
	}
}

func TestParseHexIP(t *testing.T) {
	cases := []struct {
		hex  string
		want string
	}{
		{"0101A8C0", "192.168.1.1"},
		{"00000000", "0.0.0.0"},
		{"0100007F", "127.0.0.1"},
	}
	for _, tc := range cases {
		t.Run(tc.hex, func(t *testing.T) {
			got := parseHexIP(tc.hex)
			if got != tc.want {
				t.Errorf("got %q, want %q", got, tc.want)
			}
		})
	}
}

func TestParseHexIP_InvalidLength(t *testing.T) {
	got := parseHexIP("abc")
	if got != "" {
		t.Errorf("expected empty string for invalid hex, got %q", got)
	}
}

func TestNewService(t *testing.T) {
	svc := NewService()
	if svc.resolvPath != "/etc/resolv.conf" {
		t.Errorf("resolvPath: got %q", svc.resolvPath)
	}
	if svc.interfacesDirPath != "/etc/network/interfaces.d" {
		t.Errorf("interfacesDirPath: got %q", svc.interfacesDirPath)
	}
}

func TestSetDNS_InvalidSearchDomain(t *testing.T) {
	if runtime.GOOS != "linux" {
		t.Skip("skipping Linux-only test")
	}
	svc := NewService()
	_, err := svc.SetDNS(DNSConfig{
		Nameservers: []string{"8.8.8.8"},
		Search:      []string{"example.com\nnameserver 6.6.6.6"},
	})
	if err == nil {
		t.Fatal("expected error for injected search domain")
	}
	if !errors.Is(err, errInvalidSearchDom) {
		t.Errorf("got %v, want errInvalidSearchDom", err)
	}
}

func TestValidateStaticIPRequest_IPv6Rejected(t *testing.T) {
	err := validateStaticIPRequest(StaticIPRequest{IP: "fe80::1/64", Gateway: "192.168.1.1"})
	if err != errIPv6NotSupported {
		t.Errorf("got %v, want errIPv6NotSupported", err)
	}
}

func TestNetworkPlugin_ZeroValue_Routes(t *testing.T) {
	p := &NetworkPlugin{}
	h := p.Routes()
	if h == nil {
		t.Fatal("Routes returned nil from zero-value plugin")
	}
}
