package network

import (
	"errors"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
	"time"
)

func TestListInterfaces(t *testing.T) {
	svc := NewService()
	ifaces, err := svc.ListInterfaces()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if ifaces == nil {
		t.Fatal("expected non-nil slice")
	}
	// Every system should have at least one non-loopback interface
	// (may be zero in some CI containers, so don't assert count)
	for _, iface := range ifaces {
		if iface.Name == "" {
			t.Error("interface with empty name")
		}
		if iface.State != "up" && iface.State != "down" {
			t.Errorf("interface %s: unexpected state %q", iface.Name, iface.State)
		}
	}
}

func TestGetInterface_NotFound(t *testing.T) {
	svc := NewService()
	_, err := svc.GetInterface("nonexistent_iface_99")
	if err == nil {
		t.Fatal("expected error for nonexistent interface")
	}
	if err != errIfaceNotFound {
		t.Errorf("got %v, want errIfaceNotFound", err)
	}
}

func TestValidateStaticIPRequest(t *testing.T) {
	cases := []struct {
		name    string
		req     StaticIPRequest
		wantErr error
	}{
		{"valid", StaticIPRequest{IP: "192.168.1.10/24", Gateway: "192.168.1.1"}, nil},
		{"empty_ip", StaticIPRequest{IP: "", Gateway: "192.168.1.1"}, errEmptyIP},
		{"empty_gw", StaticIPRequest{IP: "192.168.1.10/24", Gateway: ""}, errEmptyGateway},
		{"bad_cidr", StaticIPRequest{IP: "192.168.1.10", Gateway: "192.168.1.1"}, errInvalidCIDR},
		{"bad_gw", StaticIPRequest{IP: "192.168.1.10/24", Gateway: "not-an-ip"}, errInvalidGW},
		{"ipv6_gw", StaticIPRequest{IP: "192.168.1.10/24", Gateway: "::1"}, errIPv6NotSupported},
		{"cidr_v6", StaticIPRequest{IP: "::1/128", Gateway: "192.168.1.1"}, errIPv6NotSupported},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			err := validateStaticIPRequest(&tc.req)
			if err != tc.wantErr {
				t.Errorf("got %v, want %v", err, tc.wantErr)
			}
		})
	}
}

func TestSetStaticIP_NonLinux(t *testing.T) {
	if runtime.GOOS == "linux" {
		t.Skip("skipping non-Linux test on Linux")
	}
	svc := NewService()
	_, err := svc.SetStaticIP("eth0", StaticIPRequest{IP: "10.0.0.1/24", Gateway: "10.0.0.254"})
	if err != errNotLinux {
		t.Fatalf("got %v, want errNotLinux", err)
	}
}

func TestSetDNS_NonLinux(t *testing.T) {
	if runtime.GOOS == "linux" {
		t.Skip("skipping non-Linux test on Linux")
	}
	svc := NewService()
	_, err := svc.SetDNS(DNSConfig{Nameservers: []string{"8.8.8.8"}})
	if err != errNotLinux {
		t.Fatalf("got %v, want errNotLinux", err)
	}
}

func TestParseResolvConf(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "resolv.conf")

	content := `# Generated by NetworkManager
nameserver 8.8.8.8
nameserver 1.1.1.1
search local home.lan
`
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("failed to write test file: %v", err)
	}

	cfg, err := parseResolvConf(path)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(cfg.Nameservers) != 2 {
		t.Fatalf("nameservers: got %d, want 2", len(cfg.Nameservers))
	}
	if cfg.Nameservers[0] != "8.8.8.8" || cfg.Nameservers[1] != "1.1.1.1" {
		t.Errorf("nameservers: got %v", cfg.Nameservers)
	}
	if len(cfg.Search) != 2 {
		t.Fatalf("search: got %d, want 2", len(cfg.Search))
	}
	if cfg.Search[0] != "local" || cfg.Search[1] != "home.lan" {
		t.Errorf("search: got %v", cfg.Search)
	}
}

func TestParseResolvConf_MissingFile(t *testing.T) {
	cfg, err := parseResolvConf("/nonexistent/resolv.conf")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cfg.Nameservers == nil || len(cfg.Nameservers) != 0 {
		t.Errorf("expected empty nameservers, got %v", cfg.Nameservers)
	}
}

func TestParseResolvConf_EmptyFile(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "resolv.conf")
	if err := os.WriteFile(path, []byte(""), 0o644); err != nil {
		t.Fatalf("failed to write: %v", err)
	}
	cfg, err := parseResolvConf(path)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(cfg.Nameservers) != 0 {
		t.Errorf("expected empty nameservers, got %v", cfg.Nameservers)
	}
}

func TestParseResolvConf_CommentsOnly(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "resolv.conf")
	content := "# comment\n# another\n"
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("failed to write: %v", err)
	}
	cfg, err := parseResolvConf(path)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(cfg.Nameservers) != 0 {
		t.Errorf("expected empty nameservers, got %v", cfg.Nameservers)
	}
}

func TestGetDNS_WithMockPath(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "resolv.conf")
	content := "nameserver 9.9.9.9\n"
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("failed to write: %v", err)
	}

	svc := &Service{resolvPath: path}
	dns, err := svc.GetDNS()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(dns.Nameservers) != 1 || dns.Nameservers[0] != "9.9.9.9" {
		t.Errorf("nameservers: got %v, want [9.9.9.9]", dns.Nameservers)
	}
}

func TestParseHexIP(t *testing.T) {
	cases := []struct {
		hex  string
		want string
	}{
		{"0101A8C0", "192.168.1.1"},
		{"00000000", "0.0.0.0"},
		{"0100007F", "127.0.0.1"},
	}
	for _, tc := range cases {
		t.Run(tc.hex, func(t *testing.T) {
			got := parseHexIP(tc.hex)
			if got != tc.want {
				t.Errorf("got %q, want %q", got, tc.want)
			}
		})
	}
}

func TestParseHexIP_InvalidLength(t *testing.T) {
	got := parseHexIP("abc")
	if got != "" {
		t.Errorf("expected empty string for invalid hex, got %q", got)
	}
}

func TestNewService(t *testing.T) {
	svc := NewService()
	if svc.resolvPath != "/etc/resolv.conf" {
		t.Errorf("resolvPath: got %q", svc.resolvPath)
	}
	if svc.interfacesDirPath != "/etc/network/interfaces.d" {
		t.Errorf("interfacesDirPath: got %q", svc.interfacesDirPath)
	}
	if svc.cmdTimeout != defaultCmdTimeout {
		t.Errorf("cmdTimeout: got %v, want %v", svc.cmdTimeout, defaultCmdTimeout)
	}
	if svc.dnsCheckHost != defaultDNSCheckHost {
		t.Errorf("dnsCheckHost: got %q, want %q", svc.dnsCheckHost, defaultDNSCheckHost)
	}
	if svc.connectTarget != defaultConnectTarget {
		t.Errorf("connectTarget: got %q, want %q", svc.connectTarget, defaultConnectTarget)
	}
	if svc.ifdownPath != "/sbin/ifdown" {
		t.Errorf("ifdownPath: got %q", svc.ifdownPath)
	}
	if svc.ifupPath != "/sbin/ifup" {
		t.Errorf("ifupPath: got %q", svc.ifupPath)
	}
}

func TestSetDNS_InvalidSearchDomain(t *testing.T) {
	if runtime.GOOS != "linux" {
		t.Skip("skipping Linux-only test")
	}
	svc := NewService()
	_, err := svc.SetDNS(DNSConfig{
		Nameservers: []string{"8.8.8.8"},
		Search:      []string{"example.com\nnameserver 6.6.6.6"},
	})
	if err == nil {
		t.Fatal("expected error for injected search domain")
	}
	if !errors.Is(err, errInvalidSearchDom) {
		t.Errorf("got %v, want errInvalidSearchDom", err)
	}
}

func TestValidateStaticIPRequest_IPv6Rejected(t *testing.T) {
	err := validateStaticIPRequest(&StaticIPRequest{IP: "fe80::1/64", Gateway: "192.168.1.1"})
	if err != errIPv6NotSupported {
		t.Errorf("got %v, want errIPv6NotSupported", err)
	}
}

func TestNetworkPlugin_ZeroValue_Routes(t *testing.T) {
	p := &NetworkPlugin{}
	h := p.Routes()
	if h == nil {
		t.Fatal("Routes returned nil from zero-value plugin")
	}
}

func TestValidateStaticIPRequest_GWNotInSubnet(t *testing.T) {
	err := validateStaticIPRequest(&StaticIPRequest{
		IP:      "192.168.1.10/24",
		Gateway: "10.0.0.1",
	})
	if !errors.Is(err, errGWNotInSubnet) {
		t.Errorf("got %v, want errGWNotInSubnet", err)
	}
}

func TestValidateStaticIPRequest_GWEqualsIP(t *testing.T) {
	err := validateStaticIPRequest(&StaticIPRequest{
		IP:      "192.168.1.10/24",
		Gateway: "192.168.1.10",
	})
	if !errors.Is(err, errGWEqualsIP) {
		t.Errorf("got %v, want errGWEqualsIP", err)
	}
}

func TestValidateStaticIPRequest_SubnetBoundaries(t *testing.T) {
	cases := []struct {
		name    string
		ip      string
		gw      string
		wantErr error
	}{
		{"gw_at_subnet_start", "192.168.1.100/24", "192.168.1.0", nil},
		{"gw_at_subnet_end", "192.168.1.100/24", "192.168.1.255", nil},
		{"gw_just_outside", "192.168.1.100/24", "192.168.2.1", errGWNotInSubnet},
		{"narrow_slash30", "10.0.0.1/30", "10.0.0.2", nil},
		{"narrow_slash30_outside", "10.0.0.1/30", "10.0.0.5", errGWNotInSubnet},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			err := validateStaticIPRequest(&StaticIPRequest{IP: tc.ip, Gateway: tc.gw})
			if !errors.Is(err, tc.wantErr) {
				t.Errorf("got %v, want %v", err, tc.wantErr)
			}
		})
	}
}

func TestGetInterface_InvalidNameDefenseInDepth(t *testing.T) {
	svc := NewService()
	cases := []string{
		"../../../etc/passwd",
		"eth0/../shadow",
		"bad$name",
		"bad name",
		".",
		"..",
		"iface;rm -rf /",
	}
	for _, name := range cases {
		t.Run(name, func(t *testing.T) {
			_, err := svc.GetInterface(name)
			if !errors.Is(err, errInvalidIfaceName) {
				t.Errorf("GetInterface(%q): got %v, want errInvalidIfaceName", name, err)
			}
		})
	}
}

func TestGetInterface_ValidNameFormat(t *testing.T) {
	svc := NewService()
	// These are valid formats even if interfaces don't exist
	validNames := []string{"eth0", "wlan-1", "br_lan", "veth123"}
	for _, name := range validNames {
		t.Run(name, func(t *testing.T) {
			_, err := svc.GetInterface(name)
			// Should get "not found" not "invalid name"
			if errors.Is(err, errInvalidIfaceName) {
				t.Errorf("GetInterface(%q) rejected a valid name format", name)
			}
		})
	}
}

func TestAtomicWriteFile(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "testfile")
	data := []byte("hello world\n")

	if err := atomicWriteFile(path, data, 0o644); err != nil {
		t.Fatalf("atomicWriteFile: %v", err)
	}

	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}
	if string(got) != string(data) {
		t.Errorf("content: got %q, want %q", got, data)
	}

	info, err := os.Stat(path)
	if err != nil {
		t.Fatalf("Stat: %v", err)
	}
	if runtime.GOOS != "windows" && info.Mode().Perm() != 0o644 {
		t.Errorf("permissions: got %o, want 644", info.Mode().Perm())
	}
}

func TestAtomicWriteFile_Overwrite(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "testfile")

	if err := os.WriteFile(path, []byte("old content"), 0o644); err != nil {
		t.Fatal(err)
	}

	newData := []byte("new content\n")
	if err := atomicWriteFile(path, newData, 0o644); err != nil {
		t.Fatalf("atomicWriteFile: %v", err)
	}

	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != string(newData) {
		t.Errorf("got %q, want %q", got, newData)
	}
}

func TestAtomicWriteFile_NoTempLeftOnSuccess(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "testfile")

	if err := atomicWriteFile(path, []byte("data"), 0o644); err != nil {
		t.Fatal(err)
	}

	entries, _ := os.ReadDir(dir)
	for _, e := range entries {
		if strings.HasPrefix(e.Name(), ".tmp-") {
			t.Errorf("temp file left behind: %s", e.Name())
		}
	}
}

func TestAtomicWriteFile_BadDir(t *testing.T) {
	err := atomicWriteFile("/nonexistent/dir/file", []byte("data"), 0o644)
	if err == nil {
		t.Fatal("expected error for bad directory")
	}
}

func TestGetNetworkStatus_DisabledChecks(t *testing.T) {
	svc := &Service{
		dnsCheckHost:  "",
		connectTarget: "",
	}
	status, err := svc.GetNetworkStatus()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if status.DNSReachable {
		t.Error("DNSReachable should be false when check is disabled")
	}
	if status.InternetReachable {
		t.Error("InternetReachable should be false when check is disabled")
	}
}

func TestSetDNS_AtomicWrite(t *testing.T) {
	if runtime.GOOS != "linux" {
		t.Skip("skipping Linux-only test")
	}
	dir := t.TempDir()
	resolvPath := filepath.Join(dir, "resolv.conf")

	svc := &Service{resolvPath: resolvPath}
	_, err := svc.SetDNS(DNSConfig{
		Nameservers: []string{"8.8.8.8", "1.1.1.1"},
		Search:      []string{"example.com"},
	})
	if err != nil {
		t.Fatalf("SetDNS: %v", err)
	}

	got, err := os.ReadFile(resolvPath)
	if err != nil {
		t.Fatal(err)
	}
	content := string(got)
	if !strings.Contains(content, "nameserver 8.8.8.8") {
		t.Error("missing nameserver 8.8.8.8")
	}
	if !strings.Contains(content, "nameserver 1.1.1.1") {
		t.Error("missing nameserver 1.1.1.1")
	}
	if !strings.Contains(content, "search example.com") {
		t.Error("missing search domain")
	}

	// No temp files left behind
	entries, _ := os.ReadDir(dir)
	for _, e := range entries {
		if strings.HasPrefix(e.Name(), ".tmp-") {
			t.Errorf("temp file left behind: %s", e.Name())
		}
	}
}

func TestGetDNS_ConcurrentSafe(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "resolv.conf")
	if err := os.WriteFile(path, []byte("nameserver 8.8.8.8\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	svc := &Service{resolvPath: path}

	// Run concurrent reads — should not panic or deadlock
	done := make(chan struct{}, 10)
	for i := 0; i < 10; i++ {
		go func() {
			defer func() { done <- struct{}{} }()
			_, err := svc.GetDNS()
			if err != nil {
				t.Errorf("concurrent GetDNS: %v", err)
			}
		}()
	}
	for i := 0; i < 10; i++ {
		<-done
	}
}

func TestParseHexIP_InvalidChars(t *testing.T) {
	cases := []string{"ZZZZZZZZ", "0101XXXX", "gh01ij02"}
	for _, hex := range cases {
		t.Run(hex, func(t *testing.T) {
			got := parseHexIP(hex)
			if got != "" {
				t.Errorf("parseHexIP(%q) = %q, want empty", hex, got)
			}
		})
	}
}

func TestSetStaticIP_InvalidNameAtServiceLayer(t *testing.T) {
	if runtime.GOOS != "linux" {
		t.Skip("skipping Linux-only test")
	}
	dir := t.TempDir()
	svc := &Service{
		interfacesDirPath: dir,
		cmdTimeout:        5 * time.Second,
		ifdownPath:        "/sbin/ifdown",
		ifupPath:          "/sbin/ifup",
	}

	cases := []string{"../etc/passwd", "eth0;reboot", "bad name"}
	for _, name := range cases {
		t.Run(name, func(t *testing.T) {
			_, err := svc.SetStaticIP(name, StaticIPRequest{
				IP:      "192.168.1.10/24",
				Gateway: "192.168.1.1",
			})
			if !errors.Is(err, errInvalidIfaceName) {
				t.Errorf("SetStaticIP(%q): got %v, want errInvalidIfaceName", name, err)
			}
		})
	}
}

func TestSetStaticIP_SubnetMismatch(t *testing.T) {
	svc := NewService()
	_, err := svc.SetStaticIP("eth0", StaticIPRequest{
		IP:      "192.168.1.10/24",
		Gateway: "10.0.0.1",
	})
	if !errors.Is(err, errGWNotInSubnet) {
		t.Errorf("got %v, want errGWNotInSubnet", err)
	}
}

func TestValidateStaticIPRequest_IPv4MappedIPv6Canonicalized(t *testing.T) {
	// IPv4-mapped IPv6 like ::ffff:192.168.1.1 passes To4() != nil but would
	// write an invalid gateway string to the config file. The validator must
	// canonicalize it to pure IPv4 form.
	req := StaticIPRequest{
		IP:      "192.168.1.10/24",
		Gateway: "::ffff:192.168.1.1",
	}
	err := validateStaticIPRequest(&req)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if req.Gateway != "192.168.1.1" {
		t.Errorf("gateway not canonicalized: got %q, want %q", req.Gateway, "192.168.1.1")
	}
}

func TestValidateStaticIPRequest_IPv4MappedIPv6Hex(t *testing.T) {
	req := StaticIPRequest{
		IP:      "192.168.1.10/24",
		Gateway: "::ffff:c0a8:0101",
	}
	err := validateStaticIPRequest(&req)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if req.Gateway != "192.168.1.1" {
		t.Errorf("gateway not canonicalized: got %q, want %q", req.Gateway, "192.168.1.1")
	}
}

func TestValidateStaticIPRequest_GatewayEqualsIP_IPv4MappedIPv6(t *testing.T) {
	req := StaticIPRequest{
		IP:      "192.168.1.10/24",
		Gateway: "::ffff:192.168.1.10",
	}
	err := validateStaticIPRequest(&req)
	if !errors.Is(err, errGWEqualsIP) {
		t.Fatalf("expected errGWEqualsIP for IPv4-mapped gateway==IP, got %v", err)
	}
}

func TestGetInterface_ValidVLANAndAliasNames(t *testing.T) {
	svc := NewService()
	// VLAN and alias names should not be rejected by the regex
	names := []string{"eth0.100", "br0:1", "enp0s31f6.4094"}
	for _, name := range names {
		t.Run(name, func(t *testing.T) {
			_, err := svc.GetInterface(name)
			if errors.Is(err, errInvalidIfaceName) {
				t.Errorf("GetInterface(%q) rejected a valid VLAN/alias name", name)
			}
		})
	}
}

func TestGetInterfaceUnlocked_NotFound(t *testing.T) {
	svc := NewService()
	_, err := svc.getInterfaceUnlocked("nonexistent_iface_99")
	if !errors.Is(err, errIfaceNotFound) {
		t.Errorf("got %v, want errIfaceNotFound", err)
	}
}

func TestGetInterfaceUnlocked_MatchesGetInterface(t *testing.T) {
	svc := NewService()
	ifaces, err := svc.ListInterfaces()
	if err != nil || len(ifaces) == 0 {
		t.Skip("no interfaces available for comparison")
	}
	name := ifaces[0].Name

	got, err := svc.getInterfaceUnlocked(name)
	if err != nil {
		t.Fatalf("getInterfaceUnlocked(%q): %v", name, err)
	}

	want, err := svc.GetInterface(name)
	if err != nil {
		t.Fatalf("GetInterface(%q): %v", name, err)
	}

	if got.Name != want.Name || got.MAC != want.MAC || got.State != want.State {
		t.Errorf("mismatch: getInterfaceUnlocked=%+v, GetInterface=%+v", got, want)
	}
}

func TestAtomicWriteFile_PermissionError(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("skipping permission test on Windows")
	}
	// Create a read-only directory
	dir := t.TempDir()
	roDir := filepath.Join(dir, "readonly")
	if err := os.Mkdir(roDir, 0o500); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { os.Chmod(roDir, 0o700) })

	err := atomicWriteFile(filepath.Join(roDir, "file"), []byte("data"), 0o644)
	if err == nil {
		t.Fatal("expected error for read-only directory")
	}

	// Ensure no temp files left behind
	entries, _ := os.ReadDir(roDir)
	for _, e := range entries {
		if strings.HasPrefix(e.Name(), ".tmp-") {
			t.Errorf("temp file left behind: %s", e.Name())
		}
	}
}

func TestResolveSymlink(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("skipping symlink test on Windows")
	}
	dir := t.TempDir()
	realFile := filepath.Join(dir, "real.conf")
	if err := os.WriteFile(realFile, []byte("original"), 0o644); err != nil {
		t.Fatal(err)
	}
	link := filepath.Join(dir, "link.conf")
	if err := os.Symlink(realFile, link); err != nil {
		t.Fatal(err)
	}

	resolved := resolveSymlink(link)
	if resolved != realFile {
		t.Errorf("resolveSymlink: got %q, want %q", resolved, realFile)
	}

	// Non-symlink returns self
	direct := resolveSymlink(realFile)
	if direct != realFile {
		t.Errorf("resolveSymlink on regular file: got %q, want %q", direct, realFile)
	}

	// Nonexistent returns original path
	missing := resolveSymlink("/nonexistent/path")
	if missing != "/nonexistent/path" {
		t.Errorf("resolveSymlink on missing: got %q", missing)
	}

	// Symlink to nonexistent target — should follow via Readlink, not fall back
	danglingTarget := filepath.Join(dir, "does-not-exist.conf")
	danglingLink := filepath.Join(dir, "dangling.conf")
	if err := os.Symlink(danglingTarget, danglingLink); err != nil {
		t.Fatal(err)
	}
	resolved = resolveSymlink(danglingLink)
	if resolved != danglingTarget {
		t.Errorf("resolveSymlink on dangling symlink: got %q, want %q", resolved, danglingTarget)
	}
}

func TestSetDNS_ThroughSymlink(t *testing.T) {
	if runtime.GOOS != "linux" {
		t.Skip("skipping Linux-only test")
	}
	dir := t.TempDir()
	realFile := filepath.Join(dir, "real-resolv.conf")
	if err := os.WriteFile(realFile, []byte("# old\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	link := filepath.Join(dir, "resolv.conf")
	if err := os.Symlink(realFile, link); err != nil {
		t.Fatal(err)
	}

	svc := &Service{resolvPath: link}
	_, err := svc.SetDNS(DNSConfig{Nameservers: []string{"1.1.1.1"}})
	if err != nil {
		t.Fatalf("SetDNS through symlink: %v", err)
	}

	// Verify content was written to the real file
	got, err := os.ReadFile(realFile)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(got), "nameserver 1.1.1.1") {
		t.Errorf("real file missing expected content: %q", got)
	}

	// Verify symlink still exists and points to real file
	target, err := os.Readlink(link)
	if err != nil {
		t.Fatalf("symlink broken after SetDNS: %v", err)
	}
	if target != realFile {
		t.Errorf("symlink target changed: got %q, want %q", target, realFile)
	}
}

func TestBackupConfigFile_NoExistingFile(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "nonexistent")

	backupPath, err := backupConfigFile(path)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if backupPath != "" {
		t.Errorf("expected empty backup path for missing file, got %q", backupPath)
	}
}

func TestBackupConfigFile_ExistingFile(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "config")
	content := []byte("original content\n")
	if err := os.WriteFile(path, content, 0o644); err != nil {
		t.Fatal(err)
	}

	backupPath, err := backupConfigFile(path)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if backupPath != path+".bak" {
		t.Errorf("backup path: got %q, want %q", backupPath, path+".bak")
	}

	got, err := os.ReadFile(backupPath)
	if err != nil {
		t.Fatalf("reading backup: %v", err)
	}
	if string(got) != string(content) {
		t.Errorf("backup content: got %q, want %q", got, content)
	}
}

func TestRestoreConfigFile(t *testing.T) {
	dir := t.TempDir()
	configPath := filepath.Join(dir, "config")
	backupPath := configPath + ".bak"

	originalContent := []byte("original content\n")
	if err := os.WriteFile(backupPath, originalContent, 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(configPath, []byte("new content\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	if err := restoreConfigFile(backupPath, configPath); err != nil {
		t.Fatalf("restoreConfigFile: %v", err)
	}

	got, err := os.ReadFile(configPath)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != string(originalContent) {
		t.Errorf("restored content: got %q, want %q", got, originalContent)
	}

	// restoreConfigFile no longer removes the backup — caller decides.
	if _, err := os.Stat(backupPath); err != nil {
		t.Error("backup file should still exist after restore (caller removes it)")
	}
}

func TestSetStaticIP_RollbackOnIfupFailure(t *testing.T) {
	if runtime.GOOS != "linux" {
		t.Skip("skipping Linux-only test")
	}

	dir := t.TempDir()
	confPath := filepath.Join(dir, "lo")
	oldConfig := "auto lo\niface lo inet static\n    address 10.0.0.1\n    netmask 255.255.255.0\n    gateway 10.0.0.254\n"
	if err := os.WriteFile(confPath, []byte(oldConfig), 0o644); err != nil {
		t.Fatal(err)
	}

	svc := &Service{
		interfacesDirPath: dir,
		cmdTimeout:        5 * time.Second,
		ifdownPath:        "/bin/true",
		ifupPath:          "/bin/false",
	}

	_, err := svc.SetStaticIP("lo", StaticIPRequest{
		IP:      "192.168.1.10/24",
		Gateway: "192.168.1.1",
	})
	if err == nil {
		t.Fatal("expected error when ifup fails")
	}

	got, err := os.ReadFile(confPath)
	if err != nil {
		t.Fatalf("reading config after rollback: %v", err)
	}
	if string(got) != oldConfig {
		t.Errorf("config not restored after rollback:\ngot:  %q\nwant: %q", string(got), oldConfig)
	}

	// With /bin/false as ifupPath, both the initial and rollback ifup fail,
	// so the backup is preserved for manual recovery.
	if _, statErr := os.Stat(confPath + ".bak"); os.IsNotExist(statErr) {
		t.Error("backup file should be preserved when rollback ifup also fails")
	}
}

func TestSetStaticIP_RollbackAndRestoreIfupAlsoFails(t *testing.T) {
	if runtime.GOOS != "linux" {
		t.Skip("skipping Linux-only test")
	}

	dir := t.TempDir()
	confPath := filepath.Join(dir, "lo")
	oldConfig := "auto lo\niface lo inet static\n    address 10.0.0.1\n    netmask 255.255.255.0\n    gateway 10.0.0.254\n"
	if err := os.WriteFile(confPath, []byte(oldConfig), 0o644); err != nil {
		t.Fatal(err)
	}

	svc := &Service{
		interfacesDirPath: dir,
		cmdTimeout:        5 * time.Second,
		ifdownPath:        "/bin/true",
		ifupPath:          "/bin/false",
	}

	_, err := svc.SetStaticIP("lo", StaticIPRequest{
		IP:      "192.168.1.10/24",
		Gateway: "192.168.1.1",
	})
	if err == nil {
		t.Fatal("expected error when ifup fails")
	}

	errMsg := err.Error()
	if !strings.Contains(errMsg, "ifup lo failed") {
		t.Errorf("error should mention initial ifup failure: %v", err)
	}
	if !strings.Contains(errMsg, "rollback ifup also failed") {
		t.Errorf("error should mention rollback ifup failure: %v", err)
	}
}

func TestSetStaticIP_NoBackupForNewInterface(t *testing.T) {
	if runtime.GOOS != "linux" {
		t.Skip("skipping Linux-only test")
	}

	dir := t.TempDir()
	confPath := filepath.Join(dir, "lo")

	svc := &Service{
		interfacesDirPath: dir,
		cmdTimeout:        5 * time.Second,
		ifdownPath:        "/bin/true",
		ifupPath:          "/bin/false",
	}

	_, err := svc.SetStaticIP("lo", StaticIPRequest{
		IP:      "192.168.1.10/24",
		Gateway: "192.168.1.1",
	})
	if err == nil {
		t.Fatal("expected error when ifup fails")
	}

	got, err := os.ReadFile(confPath)
	if err != nil {
		t.Fatalf("reading config: %v", err)
	}
	if !strings.Contains(string(got), "192.168.1.10") {
		t.Error("new config should remain when no backup exists")
	}

	if _, statErr := os.Stat(confPath + ".bak"); !os.IsNotExist(statErr) {
		t.Error("no backup file should exist for new interface")
	}
}

func TestSetDNS_BackupFailsOnReadOnlyDir(t *testing.T) {
	if runtime.GOOS != "linux" {
		t.Skip("skipping Linux-only test")
	}

	dir := t.TempDir()
	resolvPath := filepath.Join(dir, "resolv.conf")
	originalContent := "nameserver 9.9.9.9\n"
	if err := os.WriteFile(resolvPath, []byte(originalContent), 0o644); err != nil {
		t.Fatal(err)
	}

	if err := os.Chmod(dir, 0o555); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chmod(dir, 0o755) })

	svc := &Service{resolvPath: resolvPath}
	_, err := svc.SetDNS(DNSConfig{Nameservers: []string{"8.8.8.8"}})
	if err == nil {
		t.Fatal("expected error when directory is read-only")
	}

	_ = os.Chmod(dir, 0o755)

	got, err := os.ReadFile(resolvPath)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != originalContent {
		t.Errorf("original content not preserved: got %q, want %q", got, originalContent)
	}
}

func TestDryRunStaticIP_Valid(t *testing.T) {
	dir := t.TempDir()
	confPath := filepath.Join(dir, "eth0")
	oldConfig := "auto eth0\niface eth0 inet static\n    address 10.0.0.1\n    netmask 255.255.255.0\n    gateway 10.0.0.254\n"
	if err := os.WriteFile(confPath, []byte(oldConfig), 0o644); err != nil {
		t.Fatal(err)
	}

	svc := &Service{interfacesDirPath: dir}
	result, err := svc.DryRunStaticIP("eth0", StaticIPRequest{
		IP:      "192.168.1.10/24",
		Gateway: "192.168.1.1",
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !result.Valid {
		t.Error("expected Valid=true")
	}
	if result.Current != oldConfig {
		t.Errorf("Current: got %q, want %q", result.Current, oldConfig)
	}
	if !strings.Contains(result.Proposed, "192.168.1.10") {
		t.Errorf("Proposed should contain new IP, got: %q", result.Proposed)
	}
	if !strings.Contains(result.Proposed, "gateway 192.168.1.1") {
		t.Errorf("Proposed should contain gateway, got: %q", result.Proposed)
	}
	if len(result.Changes) == 0 {
		t.Error("expected non-empty Changes")
	}

	// Verify file was NOT modified
	got, err := os.ReadFile(confPath)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != oldConfig {
		t.Errorf("dry-run should not modify file: got %q, want %q", string(got), oldConfig)
	}
}

func TestDryRunStaticIP_InvalidRequest(t *testing.T) {
	dir := t.TempDir()
	svc := &Service{interfacesDirPath: dir}

	cases := []struct {
		name string
		req  StaticIPRequest
	}{
		{"empty_ip", StaticIPRequest{IP: "", Gateway: "192.168.1.1"}},
		{"bad_cidr", StaticIPRequest{IP: "10.0.0.1", Gateway: "10.0.0.254"}},
		{"empty_gw", StaticIPRequest{IP: "192.168.1.10/24", Gateway: ""}},
		{"bad_gw", StaticIPRequest{IP: "192.168.1.10/24", Gateway: "not-an-ip"}},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			_, err := svc.DryRunStaticIP("eth0", tc.req)
			if err == nil {
				t.Error("expected validation error")
			}
		})
	}
}

func TestDryRunDNS_Valid(t *testing.T) {
	dir := t.TempDir()
	resolvPath := filepath.Join(dir, "resolv.conf")
	oldContent := "nameserver 9.9.9.9\n"
	if err := os.WriteFile(resolvPath, []byte(oldContent), 0o644); err != nil {
		t.Fatal(err)
	}

	svc := &Service{resolvPath: resolvPath}
	result, err := svc.DryRunDNS(DNSConfig{
		Nameservers: []string{"8.8.8.8", "1.1.1.1"},
		Search:      []string{"example.com"},
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !result.Valid {
		t.Error("expected Valid=true")
	}
	if result.Current != oldContent {
		t.Errorf("Current: got %q, want %q", result.Current, oldContent)
	}
	if !strings.Contains(result.Proposed, "nameserver 8.8.8.8") {
		t.Errorf("Proposed should contain nameserver, got: %q", result.Proposed)
	}
	if !strings.Contains(result.Proposed, "search example.com") {
		t.Errorf("Proposed should contain search domain, got: %q", result.Proposed)
	}
	if len(result.Changes) == 0 {
		t.Error("expected non-empty Changes")
	}

	// Verify file was NOT modified
	got, err := os.ReadFile(resolvPath)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != oldContent {
		t.Errorf("dry-run should not modify file: got %q, want %q", string(got), oldContent)
	}
}

func TestDryRunDNS_InvalidNameserver(t *testing.T) {
	dir := t.TempDir()
	svc := &Service{resolvPath: filepath.Join(dir, "resolv.conf")}

	_, err := svc.DryRunDNS(DNSConfig{
		Nameservers: []string{"not-an-ip", "8.8.8.8"},
	})
	if err == nil {
		t.Fatal("expected error for invalid nameserver")
	}
	if !errors.Is(err, errInvalidNameserver) {
		t.Errorf("got %v, want errInvalidNameserver", err)
	}
}

func TestDryRunDNS_InvalidSearchDomain(t *testing.T) {
	dir := t.TempDir()
	svc := &Service{resolvPath: filepath.Join(dir, "resolv.conf")}

	_, err := svc.DryRunDNS(DNSConfig{
		Nameservers: []string{"8.8.8.8"},
		Search:      []string{"valid.com", "inval!d"},
	})
	if err == nil {
		t.Fatal("expected error for invalid search domain")
	}
	if !errors.Is(err, errInvalidSearchDom) {
		t.Errorf("got %v, want errInvalidSearchDom", err)
	}
}

// --- DeleteStaticIP tests ---

func TestDeleteStaticIP_NonLinux(t *testing.T) {
	if runtime.GOOS == "linux" {
		t.Skip("skipping non-Linux test")
	}
	svc := NewService()
	_, err := svc.DeleteStaticIP("eth0")
	if !errors.Is(err, errNotLinux) {
		t.Errorf("got %v, want errNotLinux", err)
	}
}

func TestDeleteStaticIP_InvalidNameAtServiceLayer(t *testing.T) {
	if runtime.GOOS != "linux" {
		t.Skip("skipping Linux-only test")
	}
	svc := NewService()
	_, err := svc.DeleteStaticIP("../../etc")
	if !errors.Is(err, errInvalidIfaceName) {
		t.Errorf("got %v, want errInvalidIfaceName", err)
	}
}

func TestDryRunDeleteStaticIP_NoConfig(t *testing.T) {
	dir := t.TempDir()
	svc := &Service{interfacesDirPath: dir}
	_, err := svc.DryRunDeleteStaticIP("eth0")
	if !errors.Is(err, errNoStaticConfig) {
		t.Errorf("got %v, want errNoStaticConfig", err)
	}
}

func TestDryRunDeleteStaticIP_Valid(t *testing.T) {
	dir := t.TempDir()
	confContent := "auto eth0\niface eth0 inet static\n    address 10.0.0.1/24\n    gateway 10.0.0.254\n"
	if err := os.WriteFile(filepath.Join(dir, "eth0"), []byte(confContent), 0o644); err != nil {
		t.Fatal(err)
	}
	svc := &Service{interfacesDirPath: dir}

	result, err := svc.DryRunDeleteStaticIP("eth0")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !result.Valid {
		t.Error("expected Valid=true")
	}
	if result.Current != confContent {
		t.Errorf("Current: got %q, want %q", result.Current, confContent)
	}
	if result.Proposed != "" {
		t.Errorf("Proposed should be empty, got %q", result.Proposed)
	}
	if len(result.Changes) == 0 {
		t.Error("expected non-empty Changes")
	}
}

func TestDryRunDeleteStaticIP_InvalidName(t *testing.T) {
	svc := NewService()
	_, err := svc.DryRunDeleteStaticIP("../../etc")
	if !errors.Is(err, errInvalidIfaceName) {
		t.Errorf("got %v, want errInvalidIfaceName", err)
	}
}

// --- RollbackInterface tests ---

func TestRollbackInterface_NonLinux(t *testing.T) {
	if runtime.GOOS == "linux" {
		t.Skip("skipping non-Linux test")
	}
	svc := NewService()
	_, err := svc.RollbackInterface("eth0")
	if !errors.Is(err, errNotLinux) {
		t.Errorf("got %v, want errNotLinux", err)
	}
}

func TestRollbackInterface_InvalidNameAtServiceLayer(t *testing.T) {
	if runtime.GOOS != "linux" {
		t.Skip("skipping Linux-only test")
	}
	svc := NewService()
	_, err := svc.RollbackInterface("../../etc")
	if !errors.Is(err, errInvalidIfaceName) {
		t.Errorf("got %v, want errInvalidIfaceName", err)
	}
}

func TestDryRunRollbackInterface_NoBackup(t *testing.T) {
	dir := t.TempDir()
	svc := &Service{interfacesDirPath: dir}
	_, err := svc.DryRunRollbackInterface("eth0")
	if !errors.Is(err, errNoBackup) {
		t.Errorf("got %v, want errNoBackup", err)
	}
}

func TestDryRunRollbackInterface_Valid(t *testing.T) {
	dir := t.TempDir()
	current := "auto eth0\niface eth0 inet static\n    address 192.168.1.10/24\n    gateway 192.168.1.1\n"
	backup := "auto eth0\niface eth0 inet static\n    address 10.0.0.1/24\n    gateway 10.0.0.254\n"
	if err := os.WriteFile(filepath.Join(dir, "eth0"), []byte(current), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "eth0.bak"), []byte(backup), 0o644); err != nil {
		t.Fatal(err)
	}
	svc := &Service{interfacesDirPath: dir}

	result, err := svc.DryRunRollbackInterface("eth0")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !result.Valid {
		t.Error("expected Valid=true")
	}
	if result.Current != current {
		t.Errorf("Current: got %q, want %q", result.Current, current)
	}
	if result.Proposed != backup {
		t.Errorf("Proposed: got %q, want %q", result.Proposed, backup)
	}
	if len(result.Changes) == 0 {
		t.Error("expected non-empty Changes")
	}
}

func TestDryRunRollbackInterface_InvalidName(t *testing.T) {
	svc := NewService()
	_, err := svc.DryRunRollbackInterface("../../etc")
	if !errors.Is(err, errInvalidIfaceName) {
		t.Errorf("got %v, want errInvalidIfaceName", err)
	}
}

// --- RollbackDNS tests ---

func TestRollbackDNS_NonLinux(t *testing.T) {
	if runtime.GOOS == "linux" {
		t.Skip("skipping non-Linux test")
	}
	svc := NewService()
	_, err := svc.RollbackDNS()
	if !errors.Is(err, errNotLinux) {
		t.Errorf("got %v, want errNotLinux", err)
	}
}

func TestDryRunRollbackDNS_NoBackup(t *testing.T) {
	dir := t.TempDir()
	svc := &Service{resolvPath: filepath.Join(dir, "resolv.conf")}
	_, err := svc.DryRunRollbackDNS()
	if !errors.Is(err, errNoBackup) {
		t.Errorf("got %v, want errNoBackup", err)
	}
}

func TestDryRunRollbackDNS_Valid(t *testing.T) {
	dir := t.TempDir()
	resolvPath := filepath.Join(dir, "resolv.conf")
	bakPath := resolvPath + ".bak"

	current := "nameserver 8.8.8.8\nsearch example.com\n"
	backup := "nameserver 1.1.1.1\nsearch old.example.com\n"
	if err := os.WriteFile(resolvPath, []byte(current), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(bakPath, []byte(backup), 0o644); err != nil {
		t.Fatal(err)
	}
	svc := &Service{resolvPath: resolvPath}

	result, err := svc.DryRunRollbackDNS()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !result.Valid {
		t.Error("expected Valid=true")
	}
	if result.Current != current {
		t.Errorf("Current: got %q, want %q", result.Current, current)
	}
	if result.Proposed != backup {
		t.Errorf("Proposed: got %q, want %q", result.Proposed, backup)
	}
	if len(result.Changes) == 0 {
		t.Error("expected non-empty Changes")
	}
}

// --- safeReadFile tests ---

func TestSafeReadFile_Regular(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "test.bak")
	content := "auto eth0\niface eth0 inet static\n"
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}

	data, err := safeReadFile(path)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if string(data) != content {
		t.Errorf("got %q, want %q", data, content)
	}
}

func TestSafeReadFile_NotExist(t *testing.T) {
	_, err := safeReadFile(filepath.Join(t.TempDir(), "nope"))
	if !os.IsNotExist(err) {
		t.Fatalf("expected os.IsNotExist, got: %v", err)
	}
}

func TestSafeReadFile_Directory(t *testing.T) {
	dir := t.TempDir()
	_, err := safeReadFile(dir)
	if err == nil {
		t.Fatal("expected error for directory, got nil")
	}
	if !strings.Contains(err.Error(), "not a regular file") {
		t.Errorf("expected 'not a regular file' error, got: %v", err)
	}
}

func TestSafeReadFile_Symlink(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("skipping symlink test on Windows")
	}
	dir := t.TempDir()
	realFile := filepath.Join(dir, "real.bak")
	if err := os.WriteFile(realFile, []byte("secret"), 0o644); err != nil {
		t.Fatal(err)
	}
	link := filepath.Join(dir, "link.bak")
	if err := os.Symlink(realFile, link); err != nil {
		t.Fatal(err)
	}

	// os.OpenFile follows symlinks; f.Stat() sees the resolved regular file.
	// safeReadFile defends against non-regular files, not symlinks themselves.
	data, err := safeReadFile(link)
	if err != nil {
		t.Fatalf("unexpected error reading through symlink: %v", err)
	}
	if string(data) != "secret" {
		t.Errorf("expected 'secret', got %q", data)
	}
}

func TestSafeReadFile_EmptyFile(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "empty.bak")
	if err := os.WriteFile(path, nil, 0o644); err != nil {
		t.Fatal(err)
	}

	data, err := safeReadFile(path)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(data) != 0 {
		t.Errorf("expected empty data, got %d bytes", len(data))
	}
}

// --- restoreConfigFile tests ---

func TestRestoreConfigFile_RegularBackup(t *testing.T) {
	dir := t.TempDir()
	backup := filepath.Join(dir, "iface.bak")
	target := filepath.Join(dir, "iface")

	if err := os.WriteFile(backup, []byte("restored content"), 0o644); err != nil {
		t.Fatal(err)
	}

	if err := restoreConfigFile(backup, target); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	got, err := os.ReadFile(target)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != "restored content" {
		t.Errorf("got %q, want %q", got, "restored content")
	}
}

func TestRestoreConfigFile_BackupNotExist(t *testing.T) {
	dir := t.TempDir()
	err := restoreConfigFile(filepath.Join(dir, "nope.bak"), filepath.Join(dir, "target"))
	if err == nil {
		t.Fatal("expected error for missing backup")
	}
}

func TestRestoreConfigFile_BackupIsDirectory(t *testing.T) {
	dir := t.TempDir()
	backupDir := filepath.Join(dir, "fake.bak")
	if err := os.Mkdir(backupDir, 0o755); err != nil {
		t.Fatal(err)
	}

	err := restoreConfigFile(backupDir, filepath.Join(dir, "target"))
	if err == nil {
		t.Fatal("expected error for directory backup")
	}
	if !strings.Contains(err.Error(), "not a regular file") {
		t.Errorf("expected 'not a regular file' error, got: %v", err)
	}
}
